language: java
# trusty is required for oraclejdk9
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
after_success:
  - mvn clean cobertura:cobertura coveralls:report
